### ISSUE TITLE
Natalie breaks when using IBAnimatable

### ISSUE THREAD

**Issue by waltermvp** [krzyzanowskim/Natalie#91] opened 2017-03-15 16:45 UTC
I'm not even sure if a fix is possible since it's caused by a third party dependency. But I get build errors when Natalie generates code for a view controller that is subclassed from `AnimatableViewController` of [IBAnimatable](https://github.com/IBAnimatable/IBAnimatable)

**Comment by krzyzanowskim** [comment] 2017-03-15 16:55
what kind of errors? can you make an example project?

**Comment by cupojoe** [comment] 2017-03-15 17:07
Here is a blank project with IBAnimatable and Natalie. See if you get the error:
[IBAnimatableNatalieError.zip](https://github.com/krzyzanowskim/Natalie/files/845393/IBAnimatableNatalieError.zip)


> /Users/cupojoe/Code_Repos/NatalieError/IBAnimatableNatalieError/IBAnimatableNatalieError/Storyboards.swift:239:9: Property 'storyboardIdentifier' must be declared public because it matches a requirement in public protocol 'IdentifiableProtocol'

Edit: please, not this is a local build of Natalie based on master, since the inheritance issue (#78) hasn't made it to the build yet it would seem.

**Comment by krzyzanowskim** [comment] 2017-03-15 18:03
one more question. do you use master branch, or last release? I should do the release with the latest fixes

**Comment by cupojoe** [comment] 2017-03-15 18:07
We are using the release of IBAnimatable (Cocoa Pods) and the master of Natalie, built from source.

**Comment by phimage** [comment] 2017-05-16 14:40
the code is
```swift
output += "extension IdentifiableProtocol where Self: \(customClass) {\n"
if viewController.customModule != nil {
       output += "    var storyboardIdentifier: String? { return \"\(storyboardIdentifier)\" }\n"
} else {
       output += "    public var storyboardIdentifier: String? { return \"\(storyboardIdentifier)\" }\n"
}
```
customModule is not nil (because of IBAnimatable module is used)

I do not remember why there is this two case

**Comment by phimage** [comment] 2018-06-20 12:01
duplicate of new one with more information #124

**Closed as completed by phimage** 2018-06-20 12:01 UTC
